# Note: It requires docker-compose 1.13.0
#
# Usage: docker-compose up -d
version: "2.2"

services:
  # Selenium hub
  selenium_hub:
    image: selenium/hub:3.14.0-curium
    ports:
      - 4444:4444

  # Docker-Android for Android application testing
  nexus_7.1.1:
    image: budtmo/docker-android-x86-7.1.1
    privileged: true
    # Increase scale number if needed
    scale: 1
    depends_on:
      - selenium_hub
    ports:
      - 6081:6080
    # Change path of apk that you want to test. I use sample_apk that I provide in folder "example"
    volumes:
      - /home/juarmas/dev/workspaces/mobile/appiumexampleproject/src/main/resources/mobile/app:/root/tmp/sample_apk
      - ./video-nexus_7.1.1:/tmp/video
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - AUTO_RECORD=true


 # Docker-Android for Android application testing
  samsung_s7_9:
    image: budtmo/docker-android-x86-9.0
    privileged: true
    # Increase scale number if needed
    scale: 1
    depends_on:
      - selenium_hub
    ports:
      - 6082:6080
    # Change path of apk that you want to test. I use sample_apk that I provide in folder "example"
    volumes:
      - /home/juarmas/dev/workspaces/mobile/appiumexampleproject/src/main/resources/mobile/app:/root/tmp/sample_apk
      - ./video-nexus_7.1.1:/tmp/video
    environment:
      - DEVICE=Samsung Galaxy S7
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - AUTO_RECORD=true


